print received Remote ID messages on serial console for both MAVLink and DroneCAN
ArduPilot/ArduRemoteID pull request #100
Opened 2023-02-03 14:33 UTC by BluemarkInnovations

- existing code did only print a message on the serial console if a Remote ID message was received via DroneCAN. 
- this PR prints those messages for MAVLink too. And includes also the interface where the packet was received.

2023-03-24 01:36 UTC, tridge requested changes
it deliberately doesn't print for MAVLink as when testing in SITL Serial is running MAVLink, and the Serial.printf() corrupts the MAVLink stream, losing messages (and making a mess of the console with noise)
We could have an option bit to enable printfs, or we could make it do Serial.printf() only if Serial mavlink instance has not received any HEARTBEAT messages

2023-04-03 14:46 UTC, BluemarkInnovations commented
I have chosen to use the options variable. Also did a rebase and squash of all commits.

2023-08-28 20:59 UTC, BluemarkInnovations commented
Seems to be solved, see comment of April 3rd

2023-10-16 02:56 UTC, tridge commented
rebased and fixed conflicts

2023-10-16 02:56 UTC, tridge approved these changes

2023-10-16 02:57 UTC, merged