include multiple encoding errors in OPEN_DRONE_ID_ARM_STATUS message
ArduPilot/ArduRemoteID pull request #102
Opened 2023-02-07 10:29 UTC by BluemarkInnovations

In the current implementation, the check_parse fails on the **first** error whenit encounters bad data in one of the RID packets. 

In this PR, the function will collect all bad data errors and include the packets that fail in in the ARM status error field. This is useful in case the data stream has multiple errors. For instance if the system message has an error and the operator ID too, the current implementation would only return that the system message fails.

2023-03-05 01:45 UTC, tridge requested changes
it would be good to use strncat() instead of strcat() in case we end up with enough to overflow
should we use shorter names? like "SYS" for system?

2023-03-14 16:22 UTC, BluemarkInnovations commented
Implement a new PR with the requested changes.

- strncat is limited usable. The count applies to the source, not to the destination bytes.
- overflow of buffers is avoided.
- included Transport::arm_status_check function too.

2023-03-24 01:40 UTC, tridge commented
needs a rebase, sorry

2023-04-03 13:26 UTC, BluemarkInnovations commented
did a rebase and squashed the commits.

2023-10-14 21:52 UTC, tridge commented
@BluemarkInnovations i've cleaned up the string handling a bit

2023-10-14 21:52 UTC, tridge approved these changes

2023-10-14 22:00 UTC, merged