Parameter reset to defaults
ArduPilot/ArduRemoteID pull request #106
Opened 2023-03-15 13:08 UTC by BluemarkInnovations

This PR adds the parameter TO_DEFAULTS. If set to 1, it will reset all values to their default value. And will also set the TO_DEFAULTS parameter to 0 again. 

This is useful for ArduRemoteID devices that don't have a droneCAN interface. These devices don't have the option to configure string parameters. Of course, a user could flash the firmware via a serial interface; this parameter is a better way without reflashing firmware.

2023-03-24 00:31 UTC, tridge requested changes

2023-04-03 15:59 UTC, BluemarkInnovations commented on RemoteIDModule/parameters.cpp
> +            esp_restart(); //reset, so the init function will set it to factory defaults
Moved to the nvs_flash_erase option. This is a better and more cleaner way of getting the device to factory init state

2023-04-03 16:00 UTC, BluemarkInnovations commented
Updated PR where I implemented the nvs_flash_erase option.

2023-08-12 09:39 UTC, tridge approved these changes

2023-08-12 09:39 UTC, merged