Override pre-arm checks
ArduPilot/ArduRemoteID pull request #76
Opened 2022-10-02 17:42 UTC by BluemarkInnovations

Added a define in option.h to disable all pre-arm checks (OVERRIDE_ARM_STATUS). Default disabled, it is useful for development purposes.

2022-10-07 08:18 UTC, tridge requested changes
I think we could add a uint32 DEV_OPTIONS parameter instead, default to zero, and make one bit of that be force arming checks passed
its safe as end user can't set parameters

2023-01-10 06:23 UTC, tridge commented
@BluemarkInnovations I've implemented OPTIONS param as discussed and force pushed

2023-01-20 14:57 UTC, BluemarkInnovations commented
@tridge  I have tested your reworked PR; it works great, thanks! 

It seems to me also a good idea to set the OPEN_DRONE_ID_ARM_STATUS accordingly.  So if OPTIONS_FORCE_ARM_OK is set to 1, also set the OPEN_DRONE_ID_ARM_STATUS to good to arm. I have included that feature in the latest commit and verified with the MP RID plugin.

2023-03-24 00:14 UTC, tridge approved these changes

2023-03-24 00:14 UTC, merged